### ISSUE TITLE
Path and folder hierarchy

### ISSUE THREAD

**Issue by qazasds** [MotorCityCobra/face_ripper#2]
Thanks for creating this useful tool. Do you think it is possible to specify a PATH variable and pre-define the path and folders by default? It would be a lot easier to use this scripts.
Besides, is it possible to add a sample rate for vid-to-pic process? 1-min video generates thousands of pics in the current version.

Thank you!

**Comment by MotorCityCobra** [comment]
The paths are a pain to deal with.
I made something like this until now.  
Could it write the files on Macs, Linuxs, and PCs if they were all something like '~./Documents/vidpics/*.jpg'?
idk what works over all three operating systems.
I'll look into what can do that.

For the ungodly amount of photos created, I put a note about putting a for loop instead of the while loop that grabs every frame.  
'for i in range(1000):' to grab just 1000 frames instead of all the frames.
There probably is a command to skip frames.
I don't feel like I need a feature like that for myself when I'm making facesets.
If I have a super long video I'll cut it down in final cut pro.

The next scripts in the process cut out a lot of photos. As does the cropping program you end up training the faceset on.
I like having more than I need and being able to go back and get more.

**Comment by MotorCityCobra** [comment]
Also, you could put a for loop under the 'name' variable on line 56 of script 1.
You might have to make it generate a dictionary and number out of the name variable and make it only grab a frame from every x number and ignore every other, bud.
Sounds like a fun puzzle.

**Comment by MotorCityCobra** [comment]
i hope you didn't try any of that code.  
I messed up with that. THIS is the code that does what you wanted it to do...

		count = 0
		#every_th_frame is the number of frames grabbed. '3' grabs the 3rd, 6th, 9th... frames
		every_th_frame = 3
		while True:
			count += 1
			# Capture frame-by-frame
			ret, frame = cap.read()
			# Saves every th frame up to the 10,000th frame. Adjust accordingly
			if count > 3000:
				break
			if (count % every_th_frame == 0):
				name = ('/PATH/CREATED/FOR/FRAME/JPGS' + '/vidpics' + str(i) + '/' + str(uuid.uuid4()) + '.jpg')
				print ('Creating...' + name)
				cv2.imwrite(name, frame)
